on:
  pull_request:

jobs:
  podspec-lint:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest CocoaPods
        run: gem install cocoapods

      # lint the podspec that was modified in the PR
      - name: Get list of modified podspec files
        id: modified-podspecs
        env:
          BASE_REF: ${{ github.base_ref }}
          HEAD_REF: ${{ github.head_ref }}
        run: |
          git fetch origin $BASE_REF:local_base
          git fetch origin $HEAD_REF:local_head
          echo "files=$(git diff --name-only local_base local_head | grep .podspec$ | xargs)" >> "$GITHUB_OUTPUT"

      - name: Lint podspecs
        run: |
          for file in ${{ steps.modified-podspecs.outputs.files }}; do
            echo "Linting $file"
            pod spec lint $file
          done

  github-actions-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: actionlint
        uses: raven-actions/actionlint@v1